/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 69022813b2a96e17c9b68e2a5cfe42ca)
interface __BaseEnv_Env {
	OAUTH_ALLOW_CROSS_CLIENT_PKCE: "false";
	OAUTH_ALLOWED_DOMAINS: "jaipuria.ac.in";
	OAUTH_DEFAULT_CAMPUSES: "none";
	MCP_REQUIRE_GOOGLE_OAUTH: "true";
	MCP_SERVER_BASE_URL: "https://moodle-mcp.rehearsal-os.app";
	MCP_ALLOWED_HOSTS: "moodle-mcp.rehearsal-os.app";
	MCP_IP_RATE_LIMIT: "1200";
	MCP_RATE_LIMIT_MAX_KEYS: "16384";
	MCP_TRUST_PROXY_HEADERS: "true";
	MCP_REQUIRE_AUDIT: "true";
	MCP_OTEL_ENDPOINT: "https://otlp.eu01.nr-data.net";
	MCP_CAPTURE_IDENTITY: "true";
	MCP_CAPTURE_ARGUMENTS: "true";
	MCP_CAPTURE_RESULTS: "false";
	MCP_CAPTURE_CLIENT_IP: "true";
	MCP_CAPTURE_ARGS_MAX_BYTES: "32768";
	MCP_CAPTURE_RESULT_MAX_BYTES: "262144";
	MCP_RBAC_MODE: "enforce";
	MCP_CAMPUSES: "noida,lucknow,jaipur,indore";
	MCP_STUDENT_SELF_ACCESS: "true";
	MCP_SELF_SERVICE_ACCESS: "false";
	GATEWAY_ENFORCED: "false";
	AGENT_REPORT_QUEUE: "true";
	REPORT_PUBLIC_BASE_URL: "https://reports.tryrehearsal.ai";
	MCP_PII_REDACTION_MODE: "enforce";
	MOODLE_MCP_CONTAINER: DurableObjectNamespace<import("./src/index").MoodleMcpContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MoodleMcpContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}